### ISSUE TITLE
此仓库疑似流量耗尽

### ISSUE THREAD

**Issue by zmndan3** [TimeRainStarSky/Genshin-Voice-Model#1]
如题，已无法正常下载文件，求大佬补档
 如果可以的话希望能留一个阿里网盘或者其他可以不受流量限制的地址

错误详情 
Error downloading object: 6_809000.pth.xz (87e25e4): Smudge error: Error downloading
6_809000.pth.xz (87e25e49144f0c605e2006e1674750c1bf67d1a13598853fa3f6c45b04c6451f): batchresponse: This repository is over its data quota.Account responsible for LFS bandwidthshould purchase more data packs to restore access.

**Comment by Jackiexiao** [comment]
可以参考这个方法解决: https://stackoverflow.com/questions/62905325/this-repository-is-over-its-data-quota-account-responsible-for-lfs-bandwidth-sh

**Comment by Jackiexiao** [comment]
链接：https://pan.baidu.com/s/1PrXSTBfIrQLe65vdC8T8WQ?pwd=5bc6 
提取码：5bc6

如有侵权请联系我删除，仅做学习分享交流之用

**Comment by zmndan3** [comment]
非常感谢！谢谢大佬！
